import { Metadata } from "next/types";

export const metadata: Metadata = {
    title: "Chaitanya Karmalkar",
    description: "Generated by create next app",
};

export default function StudioLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <main className="z-20 relative">
            <div>{children}</div>
        </main>
    );
}
