import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";
import HeaderComponent from "@/components/header";
import FooterComponent from "@/components/footer";

const myFont = localFont({
    src: "../public/HousttelySignature-GOonZ.ttf",
    variable: "--font-house",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body data-barba="wrapper">
                <div className="">
                    <HeaderComponent />
                    {children}
                    <FooterComponent />
                </div>
            </body>
        </html>
    );
}
